### ISSUE TITLE
Curl in php 8 seems to break things

### ISSUE THREAD

**Issue by lassebirnbaum** [lifo101/php-cisco-ise#1]
PHP Fatal error:  Uncaught TypeError: Cannot assign CurlHandle to property Lifo\\CiscoISE\\CiscoISEClient::$lastUrl of type ?string in /var/www/vendor/lifo/php-cisco-ise/src/CiscoISEClient.php:74
Stack trace:
#0 /var/www/vendor/lifo/php-cisco-ise/src/CiscoISEClient.php(168): Lifo\\CiscoISE\\CiscoISEClient->curlInit()
#1 /var/www/vendor/lifo/php-cisco-ise/src/CiscoISEClient.php(870): Lifo\\CiscoISE\\CiscoISEClient->curl()
#2 /var/www/vendor/lifo/php-cisco-ise/src/CiscoISEClient.php(979): Lifo\\CiscoISE\\CiscoISEClient->doUpdate()
#3 /var/www/html/api/blacklist.php(113): Lifo\\CiscoISE\\CiscoISEClient->updateEndPoint()

Seems to be related to:

https://php.watch/versions/8.0/resource-CurlHandle

**Comment by lassebirnbaum** [comment]
Can be fixed by the following change

Line  167 of _CiscoISEClient.php_ changes from

`if (!is_resource($ch)) {`

to

`if (is_string($ch)) {`
